name: Publish NuGet Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Is Prerelease"
        type: boolean
        required: true
        default: true

permissions: write-all
env:
  PKG_VERSION: "2.6.${{ github.run_number }}"

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.x'
    
    - name: Build (dev)
      if: ${{ github.event_name != 'workflow_dispatch' || inputs.prerelease }}
      run: dotnet build Bitbound.SimpleMessenger.slnx --configuration Release  -p:FileVersion="${{ env.PKG_VERSION }}" -p:AssemblyVersion="${{ env.PKG_VERSION }}" -p:VersionPrefix="${{ env.PKG_VERSION }}" -p:VersionSuffix="dev"

    - name: Build (prod)
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.prerelease == false}}
      run: dotnet build Bitbound.SimpleMessenger.slnx --configuration Release  -p:FileVersion="${{ env.PKG_VERSION }}" -p:AssemblyVersion="${{ env.PKG_VERSION }}" -p:VersionPrefix="${{ env.PKG_VERSION }}"

    - name: Test
      run: dotnet test Bitbound.SimpleMessenger.slnx --configuration Release --no-build

    - name: Pack
      run: dotnet pack Bitbound.SimpleMessenger/Bitbound.SimpleMessenger.csproj --configuration Release --no-build -p:PackageVersion=${{ env.PKG_VERSION }}
    
    - name: Publish
      if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
